
# With tips from 
#
# https://github.com/lisa-lab/pylearn2/blob/master/pylearn2/scripts/tutorials/multilayer_perceptron/mlp_tutorial_part_3.yaml
#
# THEANO_FLAGS=mode=FAST_RUN,device=gpu,floatX=float32,optimizer=fast_compile python ~/Dropbox/umontreal/pylearn2/pylearn2/scripts/train.py base_conv_06.yaml
#
# Seems like this takes approximately 1GB of RAM and uses 170W on the GTX Titan Black.

!obj:pylearn2.train.Train {
    dataset: &train !obj:ift6266h15.code.pylearn2.datasets.variable_image_dataset.DogsVsCats {
        transformer: &transformer !obj:ift6266h15.code.pylearn2.datasets.variable_image_dataset.RandomCrop {
            scaled_size: 256,
            crop_size: 221,
        },
        start: 0,
        stop: 2000,
    },
    model: !obj:pylearn2.models.mlp.MLP {
        input_space: !obj:pylearn2.space.Conv2DSpace {
            shape: [221, 221],
            num_channels: 3,
            },
        layers: [!obj:pylearn2.models.mlp.ConvRectifiedLinear {
                     layer_name: 'h0',
                     output_channels: 32,
                     irange: 0.1,
                     kernel_shape: [4, 4],
                     pool_shape: [2, 2],
                     pool_stride: [2, 2]
                 },
                 !obj:pylearn2.models.mlp.ConvRectifiedLinear {
                     layer_name: 'h1',
                     output_channels: 16,
                     irange: 0.1,
                     kernel_shape: [4, 4],
                     pool_shape: [2, 2],
                     pool_stride: [2, 2]
                 },
                 !obj:pylearn2.models.mlp.ConvRectifiedLinear {
                     layer_name: 'h2',
                     output_channels: 16,
                     irange: 0.1,
                     kernel_shape: [4, 4],
                     pool_shape: [2, 2],
                     pool_stride: [2, 2]
                 },
                 !obj:pylearn2.models.mlp.ConvRectifiedLinear {
                     layer_name: 'h3',
                     output_channels: 16,
                     irange: 0.1,
                     kernel_shape: [4, 4],
                     pool_shape: [2, 2],
                     pool_stride: [2, 2]
                 },
                 !obj:pylearn2.models.mlp.RectifiedLinear {
                     layer_name: 'h4',
                     dim: 16,
                     #sparse_init: 10
                     irange: 1.0
                 },
                 !obj:pylearn2.models.mlp.RectifiedLinear {
                     layer_name: 'h5',
                     dim: 16,
                     #sparse_init: 10
                     irange: 1.0
                 },
            !obj:pylearn2.models.mlp.Softmax {
                layer_name: 'y',
                n_classes: 2,
                irange: 1.0,
            },
        ],
    },
    algorithm: !obj:pylearn2.training_algorithms.sgd.SGD {
        batch_size: &batch_size 50,
        train_iteration_mode: 'batchwise_shuffled_sequential',
#        batches_per_iter: 100,
        monitoring_batch_size: *batch_size,
#        monitoring_batches: 10,
        monitor_iteration_mode: 'batchwise_shuffled_sequential',
        #learning_rule : !obj:pylearn2.training_algorithms.learning_rule.AdaDelta {
        #},
        learning_rate: 1e-3,
        learning_rule: !obj:pylearn2.training_algorithms.learning_rule.Momentum {
            init_momentum: 0.1
        },
        monitoring_dataset: {
            'train' : *train,
            'valid': !obj:ift6266h15.code.pylearn2.datasets.variable_image_dataset.DogsVsCats {
                transformer: *transformer,
                start: 2000,
                stop: 2250,
            },
        },
        cost: !obj:pylearn2.costs.cost.SumOfCosts {
            costs: [!obj:pylearn2.costs.cost.MethodCost {
                        method: 'cost_from_X'
                    }
            ]
        },
        termination_criterion: !obj:pylearn2.termination_criteria.EpochCounter {
            max_epochs: 1000
        },
    },
    extensions: [
        !obj:pylearn2.train_extensions.best_params.MonitorBasedSaveBest {
             channel_name: 'valid_y_misclass',
             save_path: "/Tmp/debrea/cat/mod_gui_best.pkl"
        },
    ],
    save_path: "/Tmp/debrea/cat/mod_gui.pkl",
    save_freq: 20
}



